### ISSUE TITLE
About using "cuda" to test

### ISSUE THREAD

**Issue by LLMOON** [savvaki/LPDM#5]
Hello author, when I use the command : python denoise_config.py ---device "cuda"  

The terminal prompts an error : RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

Unable to use GPU, do you know how to solve this problem? 
Thank you very much for your answer.

**Comment by savvaki** [comment]
Thank you for pointing this out, I pushed a fix to `denoise_config.py` so please pull the latest version of this repository.  The change is one line as seen [here](https://github.com/savvaki/LPDM/blob/bd3800484cf9ef277c51a1f3e8b1ea98d1bc61a9/scripts/denoise_config.py#L116)

**Comment by LLMOON** [comment]
Thank you for your answer!
