### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by ws825922** [savvaki/LPDM#6]
ValueError: num_samples should be a positive integer value, but got num_samples=0
please help me，thanks。

**Comment by savvaki** [comment]
Could you help me reproduce your issue? Which script did you run to get this error? Did you place your images in the correct folders as specified in the README?

**Comment by savvaki** [comment]
I am closing this issue, if you can provide more detail please open another issue. Thanks
